# Generated by Django 5.2.15 on 2026-08-07 05:13

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


DEFAULT_UNITS = (
    ("Piece", "pcs"),
    ("Kilogram", "kg"),
    ("Liter", "l"),
    ("Box", "box"),
    ("Dozen", "dz"),
)


def seed_units(apps, schema_editor):
    Unit = apps.get_model("catalog", "Unit")
    for name, short_name in DEFAULT_UNITS:
        Unit.objects.get_or_create(
            short_name=short_name,
            defaults={"name": name, "is_active": True, "is_deleted": False},
        )


def link_product_units(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Unit = apps.get_model("catalog", "Unit")

    default_unit = Unit.objects.filter(short_name="pcs", is_deleted=False).first()
    if not default_unit:
        default_unit = Unit.objects.filter(is_deleted=False).first()

    for product in Product.objects.all():
        label = (getattr(product, "unit_label", None) or "pcs").strip().lower()
        unit = Unit.objects.filter(short_name__iexact=label, is_deleted=False).first()
        if not unit:
            unit = Unit.objects.filter(name__iexact=label, is_deleted=False).first()
        product.unit_ref_id = (unit or default_unit).id
        product.save(update_fields=["unit_ref_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("products", "0003_product_business_required"),
    ]

    operations = [
        migrations.RunPython(seed_units, noop),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="brand_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_stock",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.RenameField(
            model_name="product",
            old_name="unit",
            new_name="unit_label",
        ),
        migrations.AddField(
            model_name="product",
            name="unit_ref",
            field=models.ForeignKey(
                blank=True,
                db_column="unit_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.unit",
            ),
        ),
        migrations.RunPython(link_product_units, noop),
        migrations.RemoveField(
            model_name="product",
            name="unit_label",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="unit_ref",
            new_name="unit",
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.unit",
            ),
        ),
    ]
