# Generated by Django 5.2.15 on 2026-08-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode_product_brand_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
