# Generated by Django 5.2.15 on 2026-08-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
    ]
