# Generated by Django 5.2.17 on 2026-10-01 06:32

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_backfill_product_sale_tax_ids_from_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        # Existing product rates cannot be reconstructed reliably; leave them unknown.
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, null=True),
        ),
    ]
