# Generated by Django 5.2.15 on 2026-08-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_users', '0001_initial'),
        ('roles', '0002_role_business_scoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_user_roles', to='roles.role'),
        ),
    ]
