# Generated by Django 5.2.17 on 2026-10-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_data_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bank_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
