# Generated by Django 5.2.15 on 2026-08-07 06:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_profile_fields'),
        ('inventory', '0004_inventorystock_business_required'),
        ('invoicing', '0001_initial'),
        ('products', '0004_product_barcode_product_brand_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.BigIntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='businesses.business')),
                ('inventory_batch', models.ForeignKey(blank=True, db_column='inventory_batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='invoicing.inventorybatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ('-created_at',),
            },
        ),
    ]
