# Generated by Django 5.2.17 on 2026-10-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_business_data_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.BigIntegerField(null=True)),
                ('actor_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('record_type', models.CharField(max_length=80)),
                ('record_id', models.BigIntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='businesses.business')),
            ],
            options={
                'db_table': 'business_activity_logs',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['business', '-occurred_at'], name='activity_business_date_idx'), models.Index(fields=['business', 'area', '-occurred_at'], name='activity_business_area_idx')],
            },
        ),
    ]
