# Generated by Django 5.2.15 on 2026-08-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_profile_fields'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(blank=True, default='', max_length=50)),
                ('suffix', models.CharField(blank=True, default='', max_length=50)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('current_counter', models.PositiveIntegerField(default=1)),
                ('business', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Invoice Setting',
                'verbose_name_plural': 'Invoice Settings',
                'db_table': 'invoice_settings',
                'ordering': ('-year',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'year'), name='uniq_active_business_invoice_setting_year')],
            },
        ),
    ]
