# Generated by Django 5.2.15 on 2026-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_invoicesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesetting',
            name='end_counter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesetting',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicesetting',
            name='current_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
