# Generated by Django 5.2.15 on 2026-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_allow_multiple_invoice_settings_per_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicesetting',
            options={'ordering': ('-year', 'prefix', 'suffix'), 'verbose_name': 'Invoice Setting', 'verbose_name_plural': 'Invoice Settings'},
        ),
        migrations.AlterField(
            model_name='invoicesetting',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicesetting',
            name='current_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
