# Generated by Django 5.2.15 on 2026-08-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('purchases', '0005_purchase_total_cost_purchase_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchconsumption',
            name='purchase_item',
            field=models.ForeignKey(blank=True, db_column='purchase_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_consumptions', to='purchases.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='batchconsumption',
            name='sales_invoice_item',
            field=models.ForeignKey(blank=True, db_column='sales_invoice_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_consumptions', to='invoicing.salesinvoiceitem'),
        ),
    ]
