# Generated by Django 5.2.15 on 2026-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_purchaseinvoice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
