# Generated by Django 5.2.17 on 2026-10-01 06:32

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def backfill_gst_rate(apps, schema_editor):
    # Historical amounts are authoritative. Never consult today's category/tax.
    Model = apps.get_model("invoicing", "PurchaseInvoiceItem")
    alias = schema_editor.connection.alias
    for item in Model.objects.using(alias).all().iterator():
        tax = item.tax
        taxable = item.line_total - tax
        rate = None
        if tax == 0 and item.line_total > 0:
            rate = Decimal("0.00")
        elif tax > 0 and taxable > 0:
            inferred = (tax * 100 / taxable).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            if inferred <= Decimal("9999.99"):
                rate = inferred
        Model.objects.using(alias).filter(pk=item.pk).update(gst_rate=rate)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_allow_duplicate_purchase_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RunPython(backfill_gst_rate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, null=True),
        ),
    ]
