# Generated by Django 5.2.17 on 2026-08-06 13:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier_name', models.CharField(max_length=150)),
                ('reference_no', models.CharField(blank=True, default='', max_length=50)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.user')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchases',
                'ordering': ('-purchase_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'db_table': 'purchase_items',
            },
        ),
    ]
