# Generated by Django 5.2.17 on 2026-08-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='business',
            field=models.ForeignKey(blank=True, db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='businesses.business'),
        ),
    ]
