# Generated by Django 5.2.15 on 2026-08-07 06:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
