# Generated by Django 5.2.15 on 2026-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_business_scoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
